### ISSUE TITLE
fastjson 1.2.69 - 1.2.75版本 复现失败

### ISSUE THREAD

**Issue by cop233** [hosch3n/FastjsonVulns#1]
师傅好，我在fastjson 1.2.69 - 1.2.75版本复现失败了，是因为这个版本不存在下面这个机制吗
<img width="633" alt="image" src="https://user-images.githubusercontent.com/49428005/188858709-8fd0ee0e-6c1a-44a4-8c72-82dc3be6d95e.png">

**Comment by hosch3n** [comment]
感谢反馈，我没有仔细调试不一定对哈，似乎与这一部分有关：

https://github.com/alibaba/fastjson/compare/1.2.75...1.2.76

![Screenshot from 2022-09-08 02-25-13](https://user-images.githubusercontent.com/29953808/188952019-6c7cf86a-1f3c-491c-bbd1-cddb43555385.png)

**Comment by cop233** [comment]
是的师傅，我调试过了，确实是这部分影响的，感谢
